name: Process Content

on:
  push:
    branches:
      - main # ou master selon votre branche principale
    paths:
      - 'content/**/*.md'
  workflow_dispatch: # Permet de déclencher manuellement

permissions:
  contents: write # Ajoute les permissions nécessaires

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important pour avoir l'historique complet
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install gray-matter marked mkdirp --save-dev
      
      - name: Process Markdown content
        run: node scripts/process-content.js
      
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/assets/data/
          git commit -m "Auto-update content from Markdown files"
          git push